### ISSUE TITLE
Using SSR with Nuxt 1.4.0 "TypeError: Cannot read property 'middleware' of undefined"

### ISSUE THREAD

**Issue by curtisbelt** [Kelin2025/vue-responsive-components#1]
Hello, can you share how you implemented in Nuxt? I'm getting an error:

```log
  nuxt:render Rendering url / +7m
{ TypeError: Cannot read property 'middleware' of undefined
    at module.exports.__webpack_exports__.default (.nuxt/server.js:133:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7) statusCode: 500, name: 'TypeError' }
```

The error occurs even if I comment out the other related code and just leave:
```js
import { ResponsiveMixin } from 'vue-responsive-components';
```

Here's my vue component:

```vue
<template lang="pug">
  BaseMenu.TheFooterMenu(:links="this.footerMenuLinks")
</template>

<script>
import { ResponsiveMixin } from 'vue-responsive-components';

export default {
  name: 'TheFooterMenu',
  // mixins: [ResponsiveMixin],
  // breakpoints: {
  //   small: el => el.width <= 768
  // },
  computed: {
    footerMenuLinks() {
      return this.$store.state.menus.footerMenu;
    }
  }
};
</script>

<style scoped lang="scss">
.TheFooterMenu {
}
</style>
```

Thank you!

**Comment by Kelin2025** [comment]
I'm not getting this error 🤔   
I'll check it tomorrow

**Comment by J4si3k** [comment]
I also have the same problem

**Comment by Kelin2025** [comment]
I haven't seen an error with "middleware" but maybe [**this**](https://github.com/Kelin2025/vue-responsive-components/issues/2#issuecomment-416620480) can solve the problem

**Comment by Kelin2025** [comment]
Closed due to inactivity (from both sides)
